use SuShiX
go

-- Indexes for CHINHANH
CREATE NONCLUSTERED INDEX IND_CHINHANH_TenChiNhanh
ON CHINHANH (TenChiNhanh);

---- Indexes for HOADONTHANHTOAN
--CREATE NONCLUSTERED INDEX IND_HOADONTHANHTOAN_NgayLap
--ON HOADONTHANHTOAN (NgayLap);

--CREATE NONCLUSTERED INDEX IND_HOADONTHANHTOAN_MaChiNhanh
--ON HOADONTHANHTOAN (MaChiNhanh);

CREATE NONCLUSTERED INDEX IND_HOADONTHANHTOAN_TongTien
ON HOADONTHANHTOAN (TongTien);

-- Indexes for KHACHHANG
CREATE NONCLUSTERED INDEX IND_KHACHHANG_SDT_Email
ON KHACHHANG (SDT, Email);

-- Indexes for THETHANHVIEN
CREATE NONCLUSTERED INDEX IND_THETHANHVIEN_MaKhachHang
ON THETHANHVIEN (MaKhachHang);

-- Indexes for PHIEUDATMON
CREATE NONCLUSTERED INDEX IND_PHIEUDATMON_MaChiNhanh_NgayLap
ON PHIEUDATMON (MaChiNhanh, NgayLap);

-- Indexes for DANHGIADICHVU
CREATE NONCLUSTERED INDEX IND_DANHGIADICHVU_MaHoaDon
ON DANHGIADICHVU (MaHoaDon);

CREATE NONCLUSTERED INDEX IND_DANHGIADICHVU_DiemChatLuongMonAn_DiemGiaCa
ON DANHGIADICHVU (DiemChatLuongMonAn, DiemGiaCa);

-- Indexes for MON
CREATE NONCLUSTERED INDEX IND_MON_DanhMuc_GiaHienTai
ON MON (DanhMuc, GiaHienTai);