CREATE DATABASE SuShiX
GO
USE SuShiX;
GO

--USE master
--GO
--drop database SuShiX

-- Create Tables

-- CHINHANH Table
CREATE TABLE CHINHANH (
    MaChiNhanh INT IDENTITY(1,1) PRIMARY KEY,
    TenChiNhanh NVARCHAR(255) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    GioMoCua TIME NOT NULL,
    GioDongCua TIME NOT NULL,
    BaiXeMay BIT NOT NULL,
    BaiOTo BIT NOT NULL,
    MaNVQuanLy INT NOT NULL
);

-- BOPHAN Table
CREATE TABLE BOPHAN (
    MaBoPhan INT IDENTITY(1,1) PRIMARY KEY,
    MaChiNhanh INT NOT NULL,
    TenBoPhan NVARCHAR(255) NOT NULL,
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh)
);


-- NHANVIEN Table
CREATE TABLE NHANVIEN (
    MaNhanVien INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    Luong DECIMAL(18,2) NOT NULL,
    NgayVaoLam DATE NOT NULL,
    NgayNghiViec DATE NULL,
    SDT NVARCHAR(15) NOT NULL,
    Duong NVARCHAR(255) NOT NULL,
    Phuong NVARCHAR(255) NOT NULL,
    Quan NVARCHAR(255) NOT NULL,
    ThanhPho NVARCHAR(255) NOT NULL,
	MaBoPhan INT NOT NULL,
    FOREIGN KEY (MaBoPhan) REFERENCES BOPHAN(MaBoPhan)
);

-- LICHSULAMVIEC Table
CREATE TABLE LICHSULAMVIEC (
    MaLichSu INT IDENTITY(1,1) PRIMARY KEY,
    MaBoPhan INT NOT NULL,
    TenBoPhan NVARCHAR(255) NOT NULL,
    MaNhanVien INT NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NULL,
    FOREIGN KEY (MaBoPhan) REFERENCES BOPHAN(MaBoPhan),
    FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien)
);

-- KHACHHANG Table
CREATE TABLE KHACHHANG (
    MaKhachHang INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    SDT NVARCHAR(15) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    CCCD NVARCHAR(12) NOT NULL
);

-- THETHANHVIEN Table
CREATE TABLE THETHANHVIEN (
    MaTheThanhVien INT IDENTITY(1,1) PRIMARY KEY,
    MaKhachHang INT NOT NULL,
    NgayLap DATE NOT NULL,
    LoaiThe NVARCHAR(50) NOT NULL CHECK (LoaiThe IN ('SILVER', 'GOLD')),
    NgayDatLoaiThe DATE NOT NULL,
    DiemChiTieu INT NOT NULL,
    MaNVLapThe INT NOT NULL,
    FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
    FOREIGN KEY (MaNVLapThe) REFERENCES NHANVIEN(MaNhanVien)
);

-- PHIEUDATMON Table
CREATE TABLE PHIEUDATMON (
    MaPhieu INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATE NOT NULL,
    LoaiPhieu NVARCHAR(2) NOT NULL CHECK (LoaiPhieu IN ('GH', 'DB')),
    MaChiNhanh INT NOT NULL,
	MaKhachHang INT,
    FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
	FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang)
);

-- PHIEUDATMONGIAOHANG Table
CREATE TABLE PHIEUDATMONGIAOHANG (
    MaPhieuGiaoHang INT PRIMARY KEY, -- Shares MaPhieu from PHIEUDATMON
    DiaChiGiaoHang NVARCHAR(255) NOT NULL,
    FOREIGN KEY (MaPhieuGiaoHang) REFERENCES PHIEUDATMON(MaPhieu)
);

-- PHIEUDATBAN Table
CREATE TABLE PHIEUDATBAN (
    MaPhieuDatBan INT PRIMARY KEY, -- Shares MaPhieu from PHIEUDATMON
    SoBan INT NOT NULL,
    SoLuongKhach INT,
    NgayDat DATE,
    GioDen TIME,
    GhiChu NVARCHAR(255),
    LoaiPhieuDatBan NVARCHAR(2) NOT NULL CHECK (LoaiPhieuDatBan IN ('TC', 'TT')),
    MaNVDatBan INT,
    FOREIGN KEY (MaPhieuDatBan) REFERENCES PHIEUDATMON(MaPhieu),
    FOREIGN KEY (MaNVDatBan) REFERENCES NHANVIEN(MaNhanVien)
);

-- TAIKHOAN Table
CREATE TABLE TAIKHOAN (
    MaTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap NVARCHAR(50) NOT NULL UNIQUE,
    MatKhau NVARCHAR(255) NOT NULL,
    LoaiTaiKhoan NVARCHAR(10) NOT NULL CHECK (LoaiTaiKhoan IN ('KH', 'NV')),
    MaNguoiDung INT NOT NULL,
    FOREIGN KEY (MaNguoiDung) REFERENCES NHANVIEN(MaNhanVien),
    FOREIGN KEY (MaNguoiDung) REFERENCES KHACHHANG(MaKhachHang)
);

-- CONSTRAINTS --
-- Ràng buộc bảng CHINHANH
ALTER TABLE CHINHANH
ADD CONSTRAINT CK_CHINHANH_GioMoCua_SoVoi_GioDongCua CHECK (GioMoCua < GioDongCua);

-- Ràng buộc bảng NHANVIEN
ALTER TABLE NHANVIEN
ADD 
	CONSTRAINT CK_NHANVIEN_LuongDuong CHECK (Luong > 0),
    CONSTRAINT CK_NHANVIEN_NgayNghiViec CHECK (NgayNghiViec IS NULL OR NgayNghiViec > NgayVaoLam);

-- Ràng buộc bảng LICHSULAMVIEC
ALTER TABLE LICHSULAMVIEC
ADD CONSTRAINT CK_LICHSULAMVIEC_NgayBatDau CHECK (NgayKetThuc IS NULL OR NgayBatDau < NgayKetThuc);

-- Ràng buộc bảng THETHANHVIEN
ALTER TABLE THETHANHVIEN
ADD CONSTRAINT CK_THETHANHVIEN_DiemChiTieu CHECK (DiemChiTieu >= 0);


